#!/usr/bin/env bash
#
# Copyright 2021, Marshall McMullen <marshall.mcmullen@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under the terms of the Apache License
# as published by the Apache Software Foundation, either version 2 of the License, or (at your option) any later
# version.

set -eu

${EBASH_HOME}/bin/ebash --install-all
${EBASH_HOME}/bin/ebash --install-depends
${EBASH_HOME}/bin/ebash --install-recommends
