#!/usr/bin/env bash
#
# Copyright 2011-2018, Marshall McMullen <marshall.mcmullen@gmail.com>
# Copyright 2011-2018, SolidFire, Inc. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the Apache License
# as published by the Apache Software Foundation, either version 2 of the License, or (at your option) any later
# version.

set -eu

$(${EBASH_HOME}/bin/ebash --source)

# If ebash was able to be sourced, this should pass. If not, einfo won't be a recognized command and the set -eu above
# will ensure that it fails
einfo hi

assert_match "$(type einfo)" "einfo is a function"
