#!/bin/bash
#
# Copyright 2011-2018, Marshall McMullen <marshall.mcmullen@gmail.com>
# Copyright 2011-2018, SolidFire, Inc. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it under the terms of the Apache License
# as published by the Apache Software Foundation, either version 2 of the License, or (at your option) any later
# version.

$(${EBASH_HOME}/bin/ebash --source)

etestmsg "Creating try/catch block"

caught=0

try
{
    echo "Try block"
    exit 1
}
catch
{
    echo "Try block failed with $?"
    caught=1
}

assert_eq 1 "${caught}"
