#!/usr/bin/env bash

cd $(dirname $0)
source ../efuncs.sh || { echo "Unable to source efuncs." ; exit 1 ; }
esource *.sh

[[ -n ${2} ]] && die "etest only accepts one argument"

#-----------------------------------------------------------------------------
# TEST UTILITY FUNCTIONS
#-----------------------------------------------------------------------------

expect_true()
{
    local expression="${@}"
    edebug "$(lval expression)"

    eval "${expression}" || { eerror "Expect failed :: $(lval expression)"; return 1; }
    return 0
}

expect_false()
{
    local expression="${@}"
    edebug "$(lval expression)"

    eval "${expression}" && { eerror "Expect failed :: ! $(lval expression)"; return 1; }
    return 0
}

expect_op()
{
    compare "${@}" || { eerror "expect_op failed :: ${@}"; return 1; }
    return 0
}

expect_eq()
{
    local lh=$1
    local rh=$2
    expect_op "\"${lh}\"" "==" "\"${rh}\""
}

expect_ne()
{
    local lh=$1
    local rh=$2
    expect_op "\"${lh}\"" "!=" "\"${rh}\""
}

#-----------------------------------------------------------------------------
# MAIN
#-----------------------------------------------------------------------------

# Get all function names that begin with ETEST_ (and optionally match $1)
ETEST_FUNCTIONS=( $(declare -F | awk '$3 ~ "^ETEST" && $3 ~ "'$1'" {print $3}') )

# Figure out longest test name
ETEST_LONGEST=0
ETEST_LEN=0
for testfunc in "${ETEST_FUNCTIONS[@]}"; do
    ETEST_LEN=${#testfunc}
    (( ETEST_LEN > ETEST_LONGEST )) && ETEST_LONGEST=${ETEST_LEN}
done

# And execute them
ETEST_RC=0
for testfunc in "${ETEST_FUNCTIONS[@]}" ; do
    pad=$((ETEST_LONGEST-${#testfunc}+1))
    msg=$(printf "%s%${pad}s" "${testfunc}" " ")

    einfon "${msg}"
    ${testfunc}
    rc=$?
    ETEST_RC+=$rc
    eend $rc
done

exit ${ETEST_RC}
