#!/usr/bin/env bash

TOPDIR=$(readlink -m $(dirname $0)/..)

BASHUTILS=${TOPDIR}

source "${TOPDIR}/bashutils.sh" || { echo "Unable to source ${TOPDIR}/bashutils.sh" ; exit 1 ; }

: ${DESTDIR:=${TOPDIR}/.forge/work/image}
efreshdir "${DESTDIR}"

cp -rp *.sh bashlint ebench etest ibu "${DESTDIR}"

FILES_TO_FIX=(
    ${DESTDIR}/*.sh
    ${DESTDIR}/{bashlint,ebench,etest,ibu}
)

export BASHUTILS_VERSION=${PV}
export BASHUTILS=/sf/packages/bashutils-solidfire-${PV}

sed -i "${FILES_TO_FIX[@]}" -e 's|${BASHUTILS}|'${BASHUTILS}'|g'

# These lines are only development aids.  Once packaged, the BASHUTILS variable
# is locked in, so making it look like you can set the variable seems
# misleading.
sed -i "${FILES_TO_FIX[@]}" -e 's|: ${BASHUTILS:=$(dirname $0)}||g'
