#!/usr/bin/env bash

TOPDIR=$(readlink -m $(dirname $0)/..)

BASHUTILS_HOME=${TOPDIR}
BASHUTILS=${TOPDIR}/share

source "${BASHUTILS}/bashutils.sh" || { echo "Unable to source ${BASHUTILS}/bashutils.sh" ; exit 1 ; }

: ${PV:=9999}
: ${DESTDIR:=${TOPDIR}/.forge/work/image}
efreshdir "${DESTDIR}"

cp -rp share bin unittest *.md "${DESTDIR}"

FILES_TO_FIX=(
    ${DESTDIR}/share/*.sh
    ${DESTDIR}/bin/{bashlint,ebench,etest,ibu,bu}
    ${DESTDIR}/unittest/*
)

export BASHUTILS_VERSION=${PV}
export BASHUTILS=/sf/packages/bashutils-solidfire-${PV}

sed -i "${FILES_TO_FIX[@]}" -e 's|${BASHUTILS}|'${BASHUTILS}'|g'
sed -i "${FILES_TO_FIX[@]}" -e 's|${BASHUTILS_HOME}|'${BASHUTILS_HOME}'|g'

# These lines are only development aids.  Once packaged, the BASHUTILS variable
# is locked in, so making it look like you can set the variable seems
# misleading.
sed -i "${FILES_TO_FIX[@]}" -e 's|: ${BASHUTILS:=.*}$||g'
sed -i "${FILES_TO_FIX[@]}" -e 's|: ${BASHUTILS_HOME:=.*}$||g'
