#!/bin/sh
#
# Copyright 2021, Marshall McMullen <marshall.mcmullen@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under the terms of the Apache License
# as published by the Apache Software Foundation, either version 2 of the License, or (at your option) any later
# version.

set -e

########################################################################################################################
####
#### WARNING: This script is meant to be runnable in any Linux OS including older ones which do not have bash installed.
####
#### DO NOT change the she-bang at the top to bash.
####
########################################################################################################################

if [ -z "${EBASH_HOME}" ]; then
    EBASH_HOME="$(dirname $0)/.."
fi

${EBASH_HOME}/install/depends
${EBASH_HOME}/install/recommends
${EBASH_HOME}/install/docker-config
