#!/bin/sh

set -e

########################################################################################################################
####
#### WARNING: This script is meant to be runnable in any Linux OS including older ones which do not have bash installed.
####
#### DO NOT change the she-bang at the top to bash.
####
########################################################################################################################

#-----------------------------------------------------------------------------------------------------------------------
#
# Main
#
#-----------------------------------------------------------------------------------------------------------------------

UNAME="$(uname -s)"

if [ "${UNAME}" = "Darwin" ]; then
    DISTRO="darwin"
elif [ -e "/etc/os-release" ]; then
    DISTRO=$(awk -F'=' '/^ID=/ {print $2}' /etc/os-release | tr -d '"')
elif which lsb_release &>/dev/null; then
    DISTRO=$(lsb_release -is)
else
    DISTRO="${UNAME}"
fi

DISTRO=$(echo "${DISTRO}" | tr "[A-Z]" "[a-z]")

echo ">> Installing dependencies for ${DISTRO}"

export DEBIAN_FRONTEND=noninteractive

#----------------------------------------------------------------------------------------------------------------------
#
# Alpine Linux
#
#----------------------------------------------------------------------------------------------------------------------
if [ "${DISTRO}" = "alpine" ]; then

    echo "http://dl-3.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

    apk add                  \
        bash                 \
        coreutils            \
        curl                 \
        diffutils            \
        file                 \
        findutils            \
        gawk                 \
        grep                 \
        perl                 \
        procps               \
        util-linux           \

#----------------------------------------------------------------------------------------------------------------------
#
# Arch Linux
#
#----------------------------------------------------------------------------------------------------------------------
elif [ "${DISTRO}" = "arch" ]; then

    pacman -Syu --noconfirm --needed \
        curl                 \
        diffutils            \
        which                \

#----------------------------------------------------------------------------------------------------------------------
#
# CentOS
#
#----------------------------------------------------------------------------------------------------------------------
elif [ "${DISTRO}" = "centos" ]; then

    yum install epel-release -y

    yum install -y          \
        curl                \
        diffutils           \
        file                \
        perl                \
        which               \

#----------------------------------------------------------------------------------------------------------------------
#
# Debian
#
#----------------------------------------------------------------------------------------------------------------------
elif [ "${DISTRO}" = "debian" ]; then

    apt update

    apt install -y          \
        bsdmainutils        \
        curl                \
        file                \
        lsb-release         \
        procps              \

#----------------------------------------------------------------------------------------------------------------------
#
# Fedora
#
#----------------------------------------------------------------------------------------------------------------------
elif [ "${DISTRO}" = "fedora" ]; then

    dnf install -y          \
        curl                \
        diffutils           \
        file                \
        findutils           \
        perl-core           \
        procps              \
        which               \

#----------------------------------------------------------------------------------------------------------------------
#
# Gentoo
#
#----------------------------------------------------------------------------------------------------------------------
elif [ "${DISTRO}" = "gentoo" ]; then

    emerge --sync

    emerge --autounmask-write --autounmask-continue --noreplace --quiet \
        curl                \
        pfl                 \

#----------------------------------------------------------------------------------------------------------------------
#
# Ubuntu
#
#----------------------------------------------------------------------------------------------------------------------
elif [ "${DISTRO}" = "ubuntu" ]; then

    apt update

    apt install -y          \
        bsdmainutils        \
        curl                \
        file                \

#----------------------------------------------------------------------------------------------------------------------
#
# MacOS
#
#----------------------------------------------------------------------------------------------------------------------
elif [ "${DISTRO}" = "darwin" ]; then

    brew update-reset

    # Brew is lame. If you try to install something that's already installed it returns an error. So we have to first
    # check if it is installed and skip it if so.
    brew_install()
    {
        for pkg in "${@}"; do
            if ! brew ls --versions "${pkg}"; then
                brew install "${pkg}"
            fi
        done
    }

    brew_install             \
        bash                 \
        coreutils            \
        curl                 \
        findutils            \
        gnu-sed              \
        grep                 \

#----------------------------------------------------------------------------------------------------------------------
#
# UNKNOWN
#
#----------------------------------------------------------------------------------------------------------------------
else
    echo "Unknown OS: ${DISTRO}"
    exit 1
fi

exit 0
