#!/usr/bin/env bash
#
# Copyright 2021, Marshall McMullen <marshall.mcmullen@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under the terms of the Apache License
# as published by the Apache Software Foundation, either version 2 of the License, or (at your option) any later
# version.

: ${EBASH_HOME:=$(dirname $0)/..}
: ${EBASH:=${EBASH_HOME}/share}
source "${EBASH}/ebash.sh" || { echo "Unable to source ${EBASH}/ebash.sh" ; exit 1 ; }

opt_usage main <<'END'
This script is used to install additional recommended binaries onto a system. This is done using the portable ebash
provided `pkg_install` which deals with the package names across different distros sensibly.
END

#----------------------------------------------------------------------------------------------------------------------
#
# All
#
#----------------------------------------------------------------------------------------------------------------------

OS=$(os_pretty_name)
ebanner --uppercase "Installing recommended packages" \
    OS

# Empty list of packages that we'll add to for each distro
packages=()
if os linux; then
    packages+=( squashfs-tools )
fi

#----------------------------------------------------------------------------------------------------------------------
#
# Alpine
#
#----------------------------------------------------------------------------------------------------------------------

if os_distro alpine; then

    packages+=(
        bzip2
        cdrkit
        cpio
        debootstrap
        dialog
        docker
        gdb
        gettext
        git
        gnupg
        gzip
        iproute2
        iputils
        ncurses
        ncurses-terminfo
        net-tools
        pstree
        util-linux
        xz
    )

#----------------------------------------------------------------------------------------------------------------------
#
# Arch
#
#----------------------------------------------------------------------------------------------------------------------

elif os_distro arch; then

    pacman -Syu --overwrite "/usr/bin/docker-init" --noconfirm  docker

    packages+=(
        bzip2
        cdrkit
        cpio
        debootstrap
        dialog
        gdb
        gettext
        git
        gzip
        net-tools
        util-linux
    )

#----------------------------------------------------------------------------------------------------------------------
#
# CentOS
#
#----------------------------------------------------------------------------------------------------------------------

elif os_distro centos; then

    packages+=(
        bzip2
        cpio
        debootstrap
        dialog
        docker
        gdb
        genisoimage
        gettext
        git
        gzip
        iproute
        iptables
        ncurses
        net-tools
        psmisc
        util-linux
        xz
    )

#----------------------------------------------------------------------------------------------------------------------
#
# Debian
#
#----------------------------------------------------------------------------------------------------------------------

elif os_distro debian; then

    pkg_install apt-transport-https curl gnupg software-properties-common
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(grep -Po "VERSION_CODENAME=\K.*" /etc/os-release) stable"
    pkg_sync

    packages+=(
        bzip2
        cpio
        debootstrap
        dialog
        gdb
        genisoimage
        gettext
        git
        gzip
        iproute2
        iptables
        iputils-ping
        net-tools
        psmisc
        util-linux
        xz-utils
    )

    if os_release 11; then
        packages+=( docker-ce )
    elif os_release 12; then
        packages+=( docker.io )
    fi

#----------------------------------------------------------------------------------------------------------------------
#
# Fedora
#
#----------------------------------------------------------------------------------------------------------------------

elif os_distro fedora; then

    pkg_install dnf-plugins-core
    dnf config-manager -y --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    pkg_sync

    packages+=(
        ShellCheck
        bzip2
        containerd.io
        cpio
        debootstrap
        dialog
        docker-ce
        docker-ce-cli
        gdb
        genisoimage
        gettext
        git
        gzip
        iproute
        iptables
        iputils
        ncurses
        net-tools
        psmisc
        util-linux
        xz
    )

#----------------------------------------------------------------------------------------------------------------------
#
# Gentoo
#
#----------------------------------------------------------------------------------------------------------------------

elif os_distro gentoo; then

    portdir=$(portageq get_repo_path / gentoo)
    if [[ ! -d "${portdir}" ]]; then
        emerge-webrsync
    fi

    packages+=(
        app-arch/bzip2
        app-arch/cpio
        app-arch/gzip
        app-arch/lbzip2
        app-arch/pigz
        app-cdr/cdrtools
        app-containers/docker
        app-containers/docker-cli
        app-misc/jq
        dev-util/debootstrap
        dev-util/dialog
        dev-vcs/git
        sys-apps/net-tools
        sys-apps/util-linux
        sys-devel/gdb
        sys-devel/gettext
        sys-process/psmisc
    )

#----------------------------------------------------------------------------------------------------------------------
#
# Rocky Linux
#
#----------------------------------------------------------------------------------------------------------------------

elif os_distro rocky; then

    packages+=(
        bzip2
        cpio
        debootstrap
        dialog
        docker
        gdb
        genisoimage
        gettext
        git
        gzip
        iproute
        iptables
        ncurses
        net-tools
        psmisc
        util-linux
        xz
    )

#----------------------------------------------------------------------------------------------------------------------
#
# Ubuntu
#
#----------------------------------------------------------------------------------------------------------------------

elif os_distro ubuntu; then

    pkg_install curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(grep -Po "VERSION_CODENAME=\K.*" /etc/os-release) stable"
    pkg_sync

    packages+=(
        bzip2
        cgroup-lite
        containerd.io
        cpio
        debootstrap
        dialog
        docker-ce
        docker-ce-cli
        gdb
        gettext
        git
        gnupg-agent
        gzip
        iproute2
        iptables
        iputils-ping
        mkisofs
        net-tools
        psmisc
        util-linux
        xz-utils
    )

#----------------------------------------------------------------------------------------------------------------------
#
# MacOS (Darwin)
#
#----------------------------------------------------------------------------------------------------------------------

elif os darwin; then

    packages+=(
        bzip2
        cpio
        dialog
        gdb
        gettext
        git
        gzip
        iproute2mac
        pstree
        util-linux
    )

    if ! command_exists docker; then
        packages+=( docker docker-machine )
    fi
fi

#----------------------------------------------------------------------------------------------------------------------
#
# INSTALL
#
#----------------------------------------------------------------------------------------------------------------------

array_sort --unique packages
pkg_install "${packages[@]}"

# Also install shellcheck via helper script
${EBASH_HOME}/install/shellcheck
