name: "CI/CD"

# Controls when the action will run. Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches-ignore:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# GLobal environment variables
env:
  COLOR_DEBUG: "dim blue"
  COLUMNS: 120
  EFUNCS_COLOR: 1
  EINTERACTIVE: 1
  EPROGRESS_DELAY: 30
  EPROGRESS_INLINE: 0
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  REGISTRY: "ghcr.io"
  TERM: "xterm-256color"

#-----------------------------------------------------------------------------------------------------------------------
#
# Pipeline Jobs
#
#-----------------------------------------------------------------------------------------------------------------------
jobs:

  #---------------------------------------------------------------------------------------------------------------------
  #
  # LINUX
  #
  #---------------------------------------------------------------------------------------------------------------------
  Linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container:
          - "alpine-3.15"
          - "archlinux"
          - "debian-11"
          - "debian-12"
          - "fedora-33"
          - "fedora-35"
          # TODO: - "gentoo"
          - "rocky-9"
          - "ubuntu-20.04"
          - "ubuntu-22.04"

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CICD_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker
        run: make docker-${{ matrix.container }} pull=1 push=1

      - name: Lint
        run: make dlint-${{ matrix.container }}

      - name: Test
        run: make dtest-${{ matrix.container }} sudo=1 mountns=1 failfast=1 failout=1 failures=5 exclude=docker

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4.6.1
        with:
          name: ${{ matrix.container }}
          path: .work/docker/${{ matrix.container }}/**

  #---------------------------------------------------------------------------------------------------------------------
  #
  # MacOS
  #
  #---------------------------------------------------------------------------------------------------------------------
  MacOS:
    strategy:
      fail-fast: false
      matrix:
        os: ["15"]

    runs-on: macos-${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: install/all

      - name: Lint
        run: make lint

      # Run all unit tests. We exclude docker tests for Darwin for our CI/CD pipeline as they don't run successfully
      # inside GitHub actions though they run perfectly fine locally.
      - name: Test
        run: make test failfast=1 failout=1 failures=5 exclude=docker

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4.6.1
        with:
          name: macos-${{ matrix.os }}
          path: .work/**

  #---------------------------------------------------------------------------------------------------------------------
  #
  # Release
  #
  #---------------------------------------------------------------------------------------------------------------------
  release:
    name: "Release"
    needs: [Linux, MacOS]
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CICD_TOKEN }}

      - name: Version
        id: version
        run: |
            # Setup Git so we can commit
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"

            # Get the next version (strip quotes from pack output)
            next_version=$(bin/ebash cicd_print | grep version_tag_next | cut -d= -f2 | tr -d '"')
            echo "tag=${next_version}" >> "${GITHUB_OUTPUT}"

            # Update version files and commit
            bin/ebash cicd_update_version_files \
                --tag "${next_version}"         \
                --version-file share/VERSION    \
                --readme README.md              \
                --release-url "https://github.com/elibs/ebash/releases" \
                --commit

            # Create and push new version tag
            bin/ebash cicd_create_next_version_tag --push

      - name: Release
        run: bin/ebash cicd_release

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.CICD_TOKEN }}
