name: "CI/CD"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: '**'

# GLobal environment variables
env:
  TERM: "xterm-256color"
  COLUMNS: "120"
  EFUNCS_COLOR: "1"
  EINTERACTIVE: "0"

#----------------------------------------------------------------------------------------------------------------------
#
# Pipeline Jobs
#
#----------------------------------------------------------------------------------------------------------------------
jobs:

  #--------------------------------------------------------------------------------------------------------------------
  #
  # LINUX
  #
  #--------------------------------------------------------------------------------------------------------------------
  Linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container:
          - "alpine:3.13"
          - "alpine:3.12"
          - "archlinux"
          - "centos:8"
          - "centos:7"
          - "debian:10"
          - "debian:9"
          - "fedora:33"
          - "fedora:32"
          - "gentoo/stage3"
          - "ubuntu:20.04"
          - "ubuntu:18.04"

    container:
      image: ${{ matrix.container }}
      options: --init --interactive --privileged --tty

    steps:
      - uses: actions/checkout@v2
      - run: echo "OSNAME=$(echo ${{ matrix.container }} | sed -e 's|:|-|' -e 's|/stage3||')" >> ${GITHUB_ENV}

      - name: Install Dependencies
        run: install/all

      - name: Lint
        run: bin/bashlint

      - name: Test
        run: bin/etest --work-dir .work/output --filter dialog

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.OSNAME }}
          path: |
            .work/etest.log
            .work/etest.json
            .work/etest.xml

  #--------------------------------------------------------------------------------------------------------------------
  #
  # MacOS
  #
  #--------------------------------------------------------------------------------------------------------------------
  MacOS:
    strategy:
      matrix:
        os: ["11.0", "10.15"]
    runs-on: macos-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: install/all

      - name: Test
        run: bin/etest --work-dir .work/output --filter dialog --debug dialog

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: macos-${{ matrix.os }}
          path: |
            .work/etest.log
            .work/etest.json
            .work/etest.xml

  #--------------------------------------------------------------------------------------------------------------------
  #
  # Test Results
  #
  #--------------------------------------------------------------------------------------------------------------------
  publish-test-results:
    name: "Publish Tests Results"
    needs: [Linux, MacOS]
    runs-on: ubuntu-latest
    # the build-and-test job might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Details
        run: find artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        with:
          check_name: Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: artifacts/**/etest.xml
