name: Pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: '**'

# GLobal environment variables
env:
  TERM: "xterm-256color"
  COLUMNS: "120"
  EFUNCS_COLOR: "1"
  EINTERACTIVE: "1"

#----------------------------------------------------------------------------------------------------------------------
#
# Pipeline Jobs
#
#----------------------------------------------------------------------------------------------------------------------
jobs:

  #--------------------------------------------------------------------------------------------------------------------
  #
  # Code Coverage
  #
  #--------------------------------------------------------------------------------------------------------------------
  Coverage:
    runs-on: ubuntu-20.04


    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo bin/ebash-install-deps
          sudo apt install -y kcov

      # Run all tests through kcov coverage analyzer. Something about how kcov runs etest causes some tests to fail.
      # This isn't being done for correctness testing, only coverage testing. So explicitly exclude those tests.
      - name: Test
        run: kcov --bash-method=DEBUG coverage bin/etest --no-logfile &> /dev/null

      - name: Report
        if: always()
        run: |
          bash <(curl -s https://codecov.io/bash)

      - name: Archive
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage



  #--------------------------------------------------------------------------------------------------------------------
  #
  # LINUX
  #
  #--------------------------------------------------------------------------------------------------------------------
  Linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container:
          - "alpine:3.12"
          - "alpine:3.11"
          - "archlinux"
          - "centos:8"
          - "centos:7"
          - "debian:10"
          - "debian:9"
          - "fedora:33"
          - "fedora:32"
          - "gentoo/stage3"
          - "ubuntu:20.04"
          - "ubuntu:18.04"
          - "ubuntu:16.04"

    container:
      image: ${{ matrix.container }}
      options: --init --interactive --privileged --tty

    steps:
      - uses: actions/checkout@v2
      - run: echo "OSNAME=$(echo ${{ matrix.container }} | sed -e 's|:|-|' -e 's|/stage3||')" >> ${GITHUB_ENV}

      - name: Install Dependencies
        run: bin/ebash-install-deps

      - name: Lint
        run: bin/bashlint

      - name: Self Test
        run: bin/selftest

      - name: Test
        run: bin/etest --summary

      - name: Archive
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.OSNAME }}
          path: |
            etest.log
            etest.json

  #--------------------------------------------------------------------------------------------------------------------
  #
  # MacOS
  #
  #--------------------------------------------------------------------------------------------------------------------
  MacOS:
    strategy:
      matrix:
        os: ["11.0", "10.15"]
    runs-on: macos-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: bin/ebash-install-deps

      - name: Lint
        run: bin/bashlint

      - name: Self Test
        run: bin/selftest

      - name: Test
        run: bin/etest --summary

      - name: Archive
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: macos-${{ matrix.os }}
          path: |
            etest.log
            etest.json
