name: Pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: '**'

# GLobal environment variables
env:
  TERM: "xterm-256color"
  COLUMNS: "120"
  EFUNCS_COLOR: "1"
  EINTERACTIVE: "1"

#----------------------------------------------------------------------------------------------------------------------
#
# Pipeline Jobs
#
#----------------------------------------------------------------------------------------------------------------------
jobs:

  #--------------------------------------------------------------------------------------------------------------------
  #
  # Code Coverage
  #
  #--------------------------------------------------------------------------------------------------------------------
  Coverage:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3
      options: --init --interactive --privileged --tty --security-opt=seccomp=unconfined
    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: bin/ebash-install-deps kcov

      # Run all tests through kcov coverage analyzer.
      - name: Test
        run: bin/etest --coverage --coverage-dir coverage --coverage-publish codecov.io --filter 'array|json|opt'

      - name: Archive
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: |
            coverage
            etest.log
            etest.json

