name: Publish Docs

on:
  push:
    branches: [ master ]

jobs:

  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: bin/ebash-install-deps

      - name: Publish Docs
        run: bin/edoc --publish
