name: Publish Docs

on:
  push:
    branches: [ master ]

jobs:

  PublishDocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - container:
          image: "alpine:latest"
          options: --init --interactive --privileged --tty

      - name: Install Dependencies
        run: bin/ebash-install-deps

      - name: Publish Docs
        run: bin/edoc --publish
