name: Publish Docs

on:
  push:
    branches: [ main ]

# GLobal environment variables
env:
  TERM: "xterm-256color"
  COLUMNS: "100"
  EINTERACTIVE: "0"
  EFUNCS_COLOR: "1"
  COLOR_DEBUG: "dim blue"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  PublishDocs:
    runs-on: ubuntu-latest

    container:
      image: "alpine:latest"
      options: --init --interactive --privileged --tty

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: install/all

      - name: Publish Docs
        run: bin/edoc --publish
