name: Publish Docs

on:
  push:
    branches: [ master ]

# GLobal environment variables
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  PublishDocs:
    runs-on: ubuntu-latest

    container:
      image: "alpine:latest"
      options: --init --interactive --privileged --tty

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: bin/ebash-install-deps

      - name: Publish Docs
        run: bin/edoc --publish
